### ISSUE TITLE
What will be the python command to run lidc2dicom.py file?

### ISSUE THREAD

**Issue by monjoybme** [QIICR/lidc2dicom#4]
My LIDC-IDRI datasets (.dcm and XML files) are available in the below directory

`/Users/me/Downloads/LIDC-IDRI/LIDC-IDRI-0997/01-01-2000-96481/1491-NLSTCVOLB30F-16103`
I'm using below command to run the **lidc2dicom.py** code

`python lidc2idri.py --images-dir /Users/me/Downloads/LIDC-IDRI/  --output-dir /Users/me/Downloads/ --log  Users/me/Downloads/ `

The code is terminating without any output/error. 
1. Could you kindly tell me my command is correct or not? 

2. I also would like to know "seg_conversion_template.json" , "sr_conversion_template.json", and "GenericColors.txt". How these files have been generated? May I use same file for extracting annotated images from LIDC? 
3. The image directory basically the .dcm and xml file directory which I have downloaded from  [https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI](https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI) not from [https://drive.google.com/drive/folders/1S-Ctfko4v0ndpvNfLA0J7Q_F1Zpk4bq0](https://drive.google.com/drive/folders/1S-Ctfko4v0ndpvNfLA0J7Q_F1Zpk4bq0) 
Please confirm.

**Comment by fedorov** [comment]
> Could you kindly tell me my command is correct or not?

You need to specify which subjects should be processed, there are different options for doing that which are listed if you run converter with `--help`. For example, to do conversion for one single subject, you can do this:

```shell
python lidc2dicom.py --images-dir ~/Documents/TCIA/LIDC-IDRI --output-dir ~/Temp/LIDC_conversion5 --subjects 1
```

> I also would like to know "seg_conversion_template.json" , "sr_conversion_template.json", and "GenericColors.txt". How these files have been generated? 

The JSON files were written manually, following the definition of the parameter file for [dcmqi](https://github.com/QIICR/dcmqi). The `GenericColors.txt` is from 3D Slicer here: https://github.com/Slicer/Slicer/blob/master/Base/Logic/Resources/ColorFiles/GenericColors.txt.

> May I use same file for extracting annotated images from LIDC?

I don't understand this question.

> The image directory basically the .dcm and xml file directory which I have downloaded from https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI

The converter does not parse xml files. It is using [pylidc](https://pylidc.github.io/) to query previously parsed annotations, and converts them into DICOM segmentations.

Can you clarify what you are trying to do? The converter will generate output similar to what you already have in https://drive.google.com/drive/folders/1S-Ctfko4v0ndpvNfLA0J7Q_F1Zpk4bq0 (it has been updated since the initial release, so the output will not be identical, I am in the process of generating the updated dataset).

The purpose of this script is primarily to provide a record of how we did the conversion, to serve as an example for those who want to do similar tasks. I do not see a good reason to re-run it to do the conversion of the same dataset. What is your goal?

**Comment by monjoybme** [comment]
Thanks a lot. Now it has been cleared to me. But I have one more confusion. The Google Drive (URL: https://drive.google.com/drive/folders/1S-Ctfko4v0ndpvNfLA0J7Q_F1Zpk4bq0 ) folder, e.g., LIDC-IDRI-001, contains '.dcm' and '.json' Files. Their filename is different. It will be easy for the readers if you kindly explain:
1. How the files are renamed (e.g., Nodule 1 -Annotation 0 measurements.dcm, Nodule 1 -Annotation 0.dcm, Nodule 1 -Annotation IL057_127364 measurements.dcm.
2. Do you have any code to visualized annotated images? I tried but it showing black.

**Comment by fedorov** [comment]
The JSON files are the parameter configuration files used by dcmqi converters in the process of creating the DICOM files. .dcm files are the segmentations and structured reports with measurements and evaluations. Did you read this preprint: 

> Fedorov A, Hancock M, Clunie D, Brochhausen M, Bona J, Kirby J, Freymann J, Pieper S, Aerts H, Kikinis R, Prior F. 2018. Standardized representation of the LIDC annotations using DICOM. PeerJ Preprints 6:e27378v1 https://doi.org/10.7287/peerj.preprints.27378

It has the details. You can use 3D Slicer + QuantitativeReporting extension for visualization of the resulting DICOM data. More examples and details coming up in the next version of the preprint.

**Comment by monjoybme** [comment]
Thanks for your message. I have installed 3D Slicer but unable to install the extension. I'm getting below error:
`Ooops. Extensions can not be installed ! Extensions install directory is expected to be readable/writable/executable: /private/var/folders/nh/yztkyf6x0jj10r0n4x25gjb00000gn/T/AppTranslocation/D44571F7-FE4B-41F3-9214-161494726449/d/Slicer.app/Contents/Extensions-28062`
I'm using MAC.

**Comment by fedorov** [comment]
It looks like you opened the installer package, but did not install the Slicer application. It looks like the application in the read-only mounted volume. See [3D Slicer installation instructions](https://www.slicer.org/wiki/Documentation/4.10/SlicerApplication/Installation).

**Comment by monjoybme** [comment]
Solved this issue by dragging .dmg file into Applications folder.

**Comment by monjoybme** [comment]
Thanks a lot. I'm getting an image like below. 
<img width="1509" alt="Screen Shot 2019-03-28 at 4 02 20 PM" src="https://user-images.githubusercontent.com/17875749/55188961-02b4c100-5173-11e9-8038-5c870d52d4ec.png">

but in your paper [page number: 13], labelling has been shown on the original image. Could you tell me how can I get results like page number 13?

**Comment by fedorov** [comment]
You have to import the CT study for the patient you want to see into Slicer DICOM database before loading the segmentation. If you do that, then Slicer will be able to automatically identify and load the image as you load the segmentation.

**Comment by monjoybme** [comment]
Thank you for your prompt reply. It's working perfectly. I read your paper, but still,  I'm confused when I am trying to correlate the original image slices with the annotated images.

For an example in case of Patient ID 'LIDC-IDRI-0997', the original image folder contains almost 539 '.dcm' files (000001.dcm to 000538.dcm). But your annotated image folder contains only a few slices in which nodules are present. **Can you tell me how I can be sure which annotated .dcm file corresponds to which original.dcm file?**

**Comment by fedorov** [comment]
Although both CT and SEG are DICOM objects, they are quite different.

[DICOM Computed Tomography](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.3.html) object stores individual slices of the image as separate files.

[DICOM Segmentation](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.51.html) object is multiframe, and stores all slices in a single file.

There is no correspondence at the file level. The segmentation object references individual slices of the CT that are segmented, and the ImagePositionPatient/ImageOrientationPatient attributes can be used to establish correspondence.

If you do not need the metadata, and only concerned with the image/segmentation content, you can convert the CT and SEG series into volumetric formats, such as NIFTI or NRRD.

If you let us know more details about your goal, how you want to use the data, it would be easier to help you.

**Comment by monjoybme** [comment]
Thanks for your help. I want to use DICOM Computed Tomography object/slices (as an original image) and DICOM Segmentation object (as a ground truth image) to train a deep learning model which will detect the nodule and extract voxels around the nodule. 
This is the first time I'm working on radiology images. Hence, I couldn't understand how to handle multi-frame objects to feed into the model.

**Comment by fedorov** [comment]
Thank you, this helps. I am not working with deep learning myself, but for your purpose, I would consider one of the following:

Approach 1:
* convert CT into a 3d volume (you can use [plastimatch convert](http://plastimatch.org/plastimatch.html) for this purpose, for example)
* convert SEG into a 3d volume (you can use [dcmqi](https://github.com/qiicr/dcmqi) for this)
* use ITK (easiest probably to use [itk-python](https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html)) to read CT and segmentation volumes, find corresponding slices, extract slices from the 3d image, make numpy arrays from those and feed into the network

Approach 2 (much easier, much fewer things to learn):
* use [pylidc](https://pylidc.github.io/) to query images and segmentations, it will give you numpy arrays directly

For the LIDC collection, you are have pylidc custom python package developed for that specific collection, so Approach 2 will work.

For more general case, and for a growing number of other collections on [TCIA](https://www.cancerimagingarchive.net/), you will have no choice but use Approach 1 or its flavor. You will have to decide if learning the details and related tools for Approach 1 is worth your effort.

**Comment by monjoybme** [comment]
Thanks a lot.

**Comment by VidhiBishnoi** [comment]
Can you tell me from where I can find metadata tab-separated files for the CT images i.e the CT tables for lidc2dicom code. Iam running the code of LIDC2dicom notebook metadata verification but iam not getting from where i can get CT tables. Plz help.

**Comment by fedorov** [comment]
@VidhiBishnoi the procedure for extracting and querying metadata that was originally investigated in this repo is no longer recommended. I suggest you take a look at the [Imaging Data Commons](http://portal.imaging.datacommons.cancer.gov/) that has this specific collection, with all the DICOM metadata extracted into BigQuery tables, the [Colab notebooks](https://learn.canceridc.dev/cookbook/notebooks) that include one exploring the content of the LIDC collection, and also this [DataStudio dashboard](https://datastudio.google.com/u/0/reporting/9d9a696e-0bb9-405d-a05a-a88983a02717) (as discussed in this paper http://dx.doi.org/10.1002/mp.14445).

**Comment by VidhiBishnoi** [comment]
Thank you...Actually I'm working on lung cancer detection using machine
learning and I have already downloaded the Lung CT scan dataset from LIDC.
I want the nodule images and the data of normal and abnormal attributes.
Afterwards I will also go for deep learning.
Kindly suggest..

**Comment by VidhiBishnoi** [comment]
Hello Sir, Can you share the video of the demo practice of deep learning on
the LIDC dataset?
