### ISSUE TITLE
Acquiring the standardized version of LIDC.

### ISSUE THREAD

**Issue by MjdMahasneh** [QIICR/lidc2dicom#5]
Hello,

I am unsure whether the data available in : 
https://wiki.cancerimagingarchive.net/display/Public/LIDC-IDRI 
is the the standardized one or the raw one? it seems that the masks are in .xml format on there rather DICOMs. 

Could anyone please kindly elaborate on this.

Many thanks.

**Comment by fedorov** [comment]
You can find more details about the dataset resulting from the conversion here: https://wiki.cancerimagingarchive.net/display/DOI/Standardized+representation+of+the+TCIA+LIDC-IDRI+annotations+using+DICOM

**Comment by MjdMahasneh** [comment]
Thank you @fedorov 
 I came across this document, I also found Version 2 http://bit.ly/lidc-dicom-v2 and I was a little confused. Is that the standardized data?

**Comment by fedorov** [comment]
The final dataset, and the link to the final dataset, are here: 

Fedorov, A., Hancock, M., Clunie, D., Brochhausen, M., Bona, J., Kirby, J., Freymann, J., Pieper, S., J W L Aerts, H., Kikinis, R. & Prior, F. DICOM re-encoding of volumetrically annotated Lung Imaging Database Consortium (LIDC) nodules. Med. Phys. (2020). http://dx.doi.org/10.1002/mp.14445
